### ISSUE TITLE
File listing updates

### ISSUE THREAD

**Issue by blawney** [web-mev/mev-frontend#32]
Small UI hitch:

Steps to recreate:
- Navigate to main file browser (Files tab)
- Upload a new file (e.g. foo.tsv)
- After upload is complete, select a file type (from the dropdown) that will not validate. That is, intentionally select the wrong file type
- The failure message properly appears in the "status" column, BUT the file type remains as the wrong type 
![image](https://user-images.githubusercontent.com/6886974/154568275-9cac0090-c8ef-43fe-8971-bd8c4e579e07.png)

The database record correctly has "none/null" for the resource type since it did not properly validate. However, the frontend is persisting this incorrect dropdown value. clicking the refresh button does not fix it. Only a full page refresh resets that dropdown.

**Comment by saronnhong** [comment]
Did some digging through the code and found that the reason that the "File Type" doesn't update is because of this line, 

<img width="599" alt="Screen Shot 2022-02-24 at 2 47 30 PM" src="https://user-images.githubusercontent.com/50123485/155620789-840ec1a4-45b4-4a72-809e-ebddd372019d.png">

The ID remains in validatingInfo until the "resource_type" is set which isn't until you find a valid resource type. It is initially null when you upload the file and null if you picked an invalid type. 

I fixed this by adding another condition of checking the status message of being in "Validating" state or else it will go to "Please specify file type" like we want. 

Another problem I saw was that it was polling too quickly and would close the drop down menu before I could scroll to the bottom of the list. I changed it from 120ms to 1200ms. Not sure if this will cause any troubles else where so I wanted to make a note of it.

**Comment by blawney** [comment]
Addressed in cadc83c877d142a05a57f123ded75de9b38a529d
