### ISSUE TITLE
HCL does not work

### ISSUE THREAD

**Issue by cgirardot** [web-mev/mev-frontend#47]
Dear
I just tried using the WebMeV HCL with an expression table (4 cols: gene ids + 3 samples) but it fails with the below error:

<img width="1741" alt="Screen Shot 2022-03-18 at 15 50 04" src="https://user-images.githubusercontent.com/10990795/159025634-d10dea7a-60f4-4cbe-8b39-df4c7909cb41.png">

Any idea what s wrong? Thx!

**Comment by blawney** [comment]
Thanks for letting us know!  We have also seen this issue and we have already created a solution which will allow clustering of much larger datasets. The error you see is due to the large number of genes which consumes more memory than we initially anticipated.

We will push this new change to the server very soon (this week). I will leave a comment here at that time so that you can try again.

**Comment by blawney** [comment]
OK, changes have been pushed, so this should work now.
